### ISSUE TITLE
How to use encryption with OaepCipher

### ISSUE THREAD

**Issue by rngtng** [saml-kit/xml-kit#1]
Hey hey

I wonder how to use encryption with `OaepCipher`. I expected sth like:

```ruby
cert = OpenSSL::X509::Certificate.new(File.read("/gem/credentials/cert"))
enc = Xml::Kit::Encryption.new(body, cert.public_key, {
  asymmetric_algorithm: ::Xml::Kit::Crypto::OaepCipher::ALGORITHM
})
```

But `::Xml::Kit::Crypto::OaepCipher` has only `ALGORITHMS` and yet I can't actually read from code swapping the `asymmetric_algorithm` value would actually matter - could you please showcase, please?

**Comment by mokhan** [comment]
Hey @rngtng it looks like you found a defect when using the RSA OAEP Cipher. I am working on a patch here https://github.com/saml-kit/xml-kit/pull/2.

After I push out a new release you will be able to run:

```ruby
cert = OpenSSL::X509::Certificate.new(File.read("/gem/credentials/cert"))
enc = Xml::Kit::Encryption.new(body, cert.public_key, {
  asymmetric_algorithm: ::Xml::Kit::Crypto::OaepCipher::ALGORITHM
})
```

Thanks for your patience.

**Comment by mokhan** [comment]
Version 0.1.14 has been released.

* https://rubygems.org/gems/xml-kit/versions/0.1.14
* https://github.com/saml-kit/xml-kit/releases/tag/v0.1.14

**Comment by rngtng** [comment]
wow, thanks a lot, this was fast!
