### ISSUE TITLE
Please document a way to set digest_method and signature_method for signing

### ISSUE THREAD

**Issue by chowells79** [saml-kit/xml-kit#12]
I'm updating some code that uses rsa-sha1 for signing to use xml-kit instead of doing things more manually. One of my first tests, I noticed that it switches to rsa-sha256 by default, which breaks compatibility with some external parties we've integrated with.  I investigated the source and discovered that the class including `::Xml::Kit::Templatable` can override `digest_method` and `signature_method` to control the signing algorithms, but that interface is totally undocumented.

I would like to not depend on undocumented internals, and would really appreciate some documented way to control the signing algorithms.

**Comment by chowells79** [comment]
Whoops.  That doesn't even work quite right, due to 

```
      DIGEST_METHODS = {
        SHA1: 'http://www.w3.org/2000/09/xmldsig#SHA1',
```

The correct string for that digest method is 'http://www.w3.org/2000/09/xmldsig#sha1'.  I guess this is sneaking in an actual bug report, though the bug is still gated behind an undocumented interface.

**Comment by mokhan** [comment]
In https://github.com/saml-kit/xml-kit/pull/11 I have correct the mistake to `sha1` and documented an API for specifying the designed `digest_method` and `signature_method`.

You can now use:

```ruby
item.sign_with(key_pair, digest_method: :SHA1, signature_method: :SHA1)
```

Or you can set the digest/signature methods directly via an `attr_accessor`.

```ruby
item.digest_method = :SHA1
item.signature_method = :SHA1
```

**Comment by mokhan** [comment]
This has been published in https://rubygems.org/gems/xml-kit/versions/0.4.0.

**Comment by chowells79** [comment]
Thank you.
