### ISSUE TITLE
SymDecryption: Enable Padding = 0?

### ISSUE THREAD

**Issue by rngtng** [saml-kit/xml-kit#3]
I ran into another problem: for proper symmetric decryption I require `padding = 0`. Looking into code I found this already  as a comment here: https://github.com/saml-kit/xml-kit/blob/master/lib/xml/kit/crypto/symmetric_cipher.rb#L36

Why is it just a comment? If (not) required sth. else maybe it can be passed somehow as optional?

Thx

**Comment by mokhan** [comment]
I was confused as to whether padding was necessary when I implemented this. 

> By default encryption operations are padded using standard block padding and the padding is checked and removed when decrypting

https://ruby-doc.org/stdlib-2.5.3/libdoc/openssl/rdoc/OpenSSL/Cipher.html#method-i-padding-3D

The ruby openssl API for this is a little confusing for this. From what I currently understanding implementing your own padding can be a dangerous operation due to [oracle attacks](https://en.wikipedia.org/wiki/Padding_oracle_attack).

I will do a little bit of research to get a better understanding and then see if I can provide a safe API to allow configuring your own padding. I welcome suggestions for the desired API.

Thanks for another great challenge.

**Comment by mokhan** [comment]
Until I find a longer term strategy for custom padding, I have provided an extension point to supply your own symmetric/asymmetric algorithms. Commit is [here](https://github.com/saml-kit/xml-kit/commit/8ef2adfbc61ebadc664ca4d172de4228686f1744). 

At the moment, this change will only help for encryption, but not decryption. Please let me know if this is useful to you.

**Comment by rngtng** [comment]
Thanks again for you quick response and work.. unfortunately I need it for decryption. Currently I monkey patched `decrypt` of `SymmetricCipher` to remove the comment of `# cipher.padding = 0`. I'm decrypting a server response SOAP ws-security message, which `mechanism` I can't change... Weird there's no standard or this padding information can't be extracted from the payload...

**Comment by mokhan** [comment]
Yes, I agree a standard for this would be helpful. I will attempt to create an extension point so that you do not need to monkey patch. 

Thanks again for reporting this and for your patience.

**Comment by mokhan** [comment]
Hi @rngtng, 

I have been travelling the past week so I apologise for the delayed response to this issue.

I've made a couple of changes in the `master` branch that will hopefully help. The `Xml::Kit::Decryption` class now supports a `cipher_registry` parameter. The intention of this parameter is to allow clients to use their own customer ciphers and to extend the default ciphers that are available, if needed.

Also, I have decided to leave the default padding for AES-*-CBC ciphers. As per:

```text
By default encryption operations are padded using standard block padding and the padding is checked and removed when decrypting.
```
https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html#method-i-padding-3D

However, I have opened up the `Xml::Kit::SymmetricCipher` class up to take a `padding` parameter. The default padding value is set to `nil` which signals to openssl binding to remove any padding during decrypt. If a custom padding is specified I am removing the custom padding bytes as per:

```text
5.2.1 Padding
Since the data being encrypted is an arbitrary number of octets, it may not be a multiple of the block size. This is solved by padding the plain text up to the block size before encryption and unpadding after decryption. The padding algorithm is to calculate the smallest non-zero number of octets, say N, that must be suffixed to the plain text to bring it up to a multiple of the block size. We will assume the block size is B octets so N is in the range of 1 to B. Pad by suffixing the plain text with N-1 arbitrary pad bytes and a final byte whose value is N. On decryption, just take the last byte and, after sanity checking it, strip that many bytes from the end of the decrypted cipher text.

For example, assume an 8 byte block size and plain text of 0x616263. The padded plain text would then be 0x616263????????05 where the "??" bytes can be any value. Similarly, plain text of 0x2122232425262728 would be padded to 0x2122232425262728??????????????08.
```
https://www.w3.org/TR/xmlenc-core1/#sec-Padding

If you're able to, could you please try the `master` branch to see if this works for you:

```ruby
cipher_registry = Xml::Kit::Crypto.cipher_registry do |algorithm, key|                                                                                                                                                               
  if algorithm == 'http://www.w3.org/2001/04/xmlenc#aes128-cbc'
    Xml::Kit::Crypto::SymmetricCipher.new(algorithm, key, 0)
  else
    Xml::Kit::Crypto.cipher_for(algorithm, key)
  end
end
decryption = Xml::Kit::Decryption.new(cipher_registry: cipher_registry, private_keys: private_keys)
```

If you're still having trouble, could you please share a sample encrypted document, insecure key and expected output that I could use for reproducing locally.

Thanks very much!

💎

**Comment by mokhan** [comment]
I have released version https://rubygems.org/gems/xml-kit/versions/0.2.0 which includes the changes described above.

**Comment by rngtng** [comment]
hey @mokhan - sorry my late reply, was busy, but finally able to test it. I must say again: great work! works very nice! Thanks a lot!

Btw.  I updated the registry to this in order to not have the algorithm string exposed:

```ruby
cipher_registry = Xml::Kit::Crypto.cipher_registry do |algorithm, key|
          if Xml::Kit::Crypto::SymmetricCipher.matches?(algorithm)
            Xml::Kit::Crypto::SymmetricCipher.new(algorithm, key, 0)
          else
            Xml::Kit::Crypto.cipher_for(algorithm, key)
          end
        end
```
