### ISSUE TITLE
Suggestions for some minor tweaks

### ISSUE THREAD

**Issue by rngtng** [saml-kit/xml-kit#6]
After a couple of experiments I got the setup in a use state. It now looks like:

```ruby
data_id =  ::Xml::Kit::Id.generate
key_info = ::Xml::Kit::KeyInfo.new(x509: @encryption_certificate.x509) do |x|
  x.encrypted_key = ::Xml::Kit::EncryptedKey.new(
    asymmetric_cipher: ::Xml::Kit::Crypto.cipher_for(
      ::Xml::Kit::Crypto::OaepCipher::ALGORITHM, x.x509_data.public_key
    ),
    symmetric_cipher: ::Xml::Kit::Crypto::SymmetricCipher.new
  )
end

encrypted_data = Xml::Kit::EncryptedData.new(raw_xml,
  symmetric_cipher:  key_info.encrypted_key.symmetric_cipher,
  asymmetric_cipher: key_info.encrypted_key.asymmetric_cipher,
  key_info: key_info
)
```

After that I can render the request just based on `encrypted_data` object. That's nice, although I see some minor tweaks!?

- [x] Set `symmetric_cipher` to default value: `::Xml::Kit::Crypto::SymmetricCipher.new` for `EncryptedKey` (and/or `EncryptedData`). 
- [x] Add `id` to `EncryptedData` in similar manner as `EncryptedKey`
- [ ] Extend `EncryptedData` constructor: either allow `x509_data` to be set, or set cyphers based on given key_info?

with that setup could be shrunk down to e.g.

```ruby
key_info = ::Xml::Kit::KeyInfo.new(x509: @encryption_certificate.x509) do |x|
  x.encrypted_key = ::Xml::Kit::EncryptedKey.new(
    asymmetric_cipher: ::Xml::Kit::Crypto.cipher_for(
      ::Xml::Kit::Crypto::OaepCipher::ALGORITHM, x.x509_data.public_key
    )
  )
end

encrypted_data = Xml::Kit::EncryptedData.new(raw_xml, key_info: key_info)
```

Lastly a question on how are `EncryptedKey` and `KeyInfo` hierarchal associated -
`EncryptedKey` -> `KeyInfo` or `KeyInfo` <-`EncryptedKey`? I saw `key_info` on `EncryptedKey` but IMHO it's never set..?

Let me know what you think and I'm happy to provide a PR! Thanks again

**Comment by mokhan** [comment]
> Set symmetric_cipher to default value: ::Xml::Kit::Crypto::SymmetricCipher.new for EncryptedKey (and/or EncryptedData).

I agree.

> Add id to EncryptedData in similar manner as EncryptedKey

I agree.

> Extend EncryptedData constructor: either allow x509_data to be set, or set cyphers based on given key_info?

I need to think about this.

> Lastly a question on how are EncryptedKey and KeyInfo hierarchal associated -
EncryptedKey -> KeyInfo or KeyInfo <-EncryptedKey? I saw key_info on EncryptedKey but IMHO it's never set..?

I need to dig into this. I may have made a mistake with this.

PR's are always welcome. I will be travelling again next week but more than happy to review. 

Thank you again for the fantastic feedback.

**Comment by rngtng** [comment]
Ah just figured why `KeyInfo` is on `EncryptedKey` as it's required for rendering.. For just build up the datastructure (that's what I'm currently do ^^) it's not required.. so forget my last question then..

**Comment by mokhan** [comment]
> Extend EncryptedData constructor: either allow x509_data to be set, or set cyphers based on given key_info?

Could you show me an example of what you mean?

**Comment by mokhan** [comment]
I have released [0.3.1](https://rubygems.org/gems/xml-kit/versions/0.3.1).

**Comment by mokhan** [comment]
In https://github.com/saml-kit/xml-kit/pull/11 I have updated `EncryptedData` to set the ciphers based on the key info provided.

**Comment by mokhan** [comment]
This change has been published in https://rubygems.org/gems/xml-kit/versions/0.4.0.
